# -*- coding: utf-8 -*-

"""
Final locked TRUST modeling and evaluation script

Primary clinical outcome:
    TRUST titer >= 1:16

Main purposes:
    1. Reproduce the final TRUST Random Forest workflow.
    2. Generate the five-fold cross-validation statistics reported in Table 2.
    3. Generate Figure 4a-d and Figure 4f.
    4. Generate feature importance for Supplementary Figure 2.

Figure 4 panels generated by this script:
    Figure 4a: ROC curve
    Figure 4b: Precision-recall curve
    Figure 4c: Calibration plot
    Figure 4d: Prediction-probability distribution
    Figure 4f: Decision-curve analysis
"""

import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_validate
)

from sklearn.ensemble import RandomForestClassifier

from sklearn.preprocessing import (
    OneHotEncoder,
    OrdinalEncoder
)

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import (
    LinearRegression,
    LogisticRegression
)

from sklearn.calibration import calibration_curve

from sklearn.metrics import (
    accuracy_score,
    recall_score,
    precision_score,
    f1_score,
    roc_auc_score,
    roc_curve,
    precision_recall_curve,
    average_precision_score,
    confusion_matrix,
    brier_score_loss,
    log_loss
)

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline

# ============================================================
# Global plotting settings
# ============================================================

plt.style.use("seaborn-v0_8-white")

# Retain all four plot borders.
sns.despine(
    top=False,
    right=False,
    left=False,
    bottom=False
)

plt.rcParams["axes.grid"] = False
plt.rcParams["axes.linewidth"] = 1.5
plt.rcParams["xtick.major.width"] = 1.5
plt.rcParams["ytick.major.width"] = 1.5

plt.rcParams["font.family"] = "serif"
plt.rcParams["font.serif"] = [
    "Times New Roman",
    "DejaVu Serif"
]

plt.rcParams["font.size"] = 12
plt.rcParams["axes.unicode_minus"] = False
plt.rcParams["figure.figsize"] = (9, 8)

# ============================================================
# Output directories
# ============================================================

RESULT_DIR = Path("results_TRUST")
FIGURE_DIR = RESULT_DIR / "figures"
MODEL_DIR = Path("models")

RESULT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

FIGURE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

SAVE_KW = dict(
    dpi=300,
    bbox_inches="tight",
    facecolor="white"
)

# ============================================================
# Color definitions
# ============================================================

COLOR_ROC = "#1f77b4"
COLOR_PR = "#ff7f0e"
COLOR_CAL = "#2ca02c"
COLOR_NEG = "#1f77b4"
COLOR_POS = "#ff7f0e"
COLOR_DCA = "#9467bd"

# ============================================================
# Data loading and outcome definition
# ============================================================

print("=" * 70)
print("TRUST Random Forest analysis")
print("=" * 70)

df = pd.read_csv(
    "train_data.csv",
    encoding="utf-8"
)

cat_cols = [
    "SEX",
    "DEPT",
    "DIAGNOSIS"
]

ordinal_cols = [
    "TPPA"
]

num_cols = [
    "AGE",
    "TP-Ab",
    "HIV",
    "WBC",
    "RBC",
    "PLT",
    "NEUT",
    "LYM",
    "NLR"
]

feature_cols = (
    cat_cols
    + ordinal_cols
    + num_cols
)

target_col = "TRUST"

X = df[
    feature_cols
].copy()

# Primary clinical target: TRUST titer >= 1:16
y = (
    df[target_col] >= 16
).astype(int)

print(
    f"Dataset N: {len(y)}"
)

print(
    f"Positive cases: {int(y.sum())}"
)

print(
    f"Outcome prevalence: "
    f"{y.mean():.4f} "
    f"({y.mean():.2%})"
)

# ============================================================
# Prespecified stratified 4:1 split
# ============================================================

X_train, X_test, y_train, y_test = (
    train_test_split(
        X,
        y,
        test_size=0.20,
        random_state=42,
        stratify=y
    )
)

print(
    f"Training partition N: "
    f"{len(y_train)}"
)

print(
    f"Held-out validation partition N: "
    f"{len(y_test)}"
)

print(
    f"Held-out event prevalence: "
    f"{y_test.mean():.4f}"
)

# ============================================================
# Preprocessing definition
# ============================================================
# Preprocessing is embedded in the Pipeline and is therefore
# fitted using training data only.
# ============================================================

tppa_categories = [
    ["-1", "0", "1", "2"]
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            cat_cols
        ),
        (
            "ord",
            OrdinalEncoder(
                categories=tppa_categories,
                handle_unknown="use_encoded_value",
                unknown_value=-1
            ),
            ordinal_cols
        ),
        (
            "num",
            SimpleImputer(
                strategy="median"
            ),
            num_cols
        )
    ],
    remainder="drop"
)

# ============================================================
# Final RF hyperparameters
# ============================================================
# These parameters were selected previously during the
# expanded hyperparameter-search stage and are fixed here.
# ============================================================

best_params = {
    "n_estimators": 100,
    "max_depth": 10,
    "min_samples_split": 10,
    "min_samples_leaf": 2,
    "class_weight": "balanced",
    "max_features": "sqrt"
}

# ============================================================
# Final modeling Pipeline
# ============================================================

pipeline = ImbPipeline(
    steps=[
        (
            "prep",
            preprocessor
        ),
        (
            "smote",
            SMOTE(
                random_state=42
            )
        ),
        (
            "clf",
            RandomForestClassifier(
                random_state=42,
                n_jobs=1,
                **best_params
            )
        )
    ]
)

# ============================================================
# Five-fold cross-validation in the training partition
# ============================================================
# These statistics are used for Table 2.
# Preprocessing and SMOTE remain inside each CV fold because
# both steps are embedded in the imbalanced-learn Pipeline.
# ============================================================

cv = StratifiedKFold(
    n_splits=5,
    shuffle=False
)

scoring = {
    "roc_auc": "roc_auc",
    "accuracy": "accuracy",
    "recall": "recall",
    "precision": "precision",
    "f1": "f1"
}

cv_results = cross_validate(
    pipeline,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    return_train_score=False,
    n_jobs=1
)

# ============================================================
# Table 2 calculation
# ============================================================

try:
    from scipy.stats import t

    t_crit = t.ppf(
        0.975,
        df=4
    )

except ImportError:
    t_crit = 1.96


metric_mapping = {
    "AUROC": cv_results["test_roc_auc"],
    "Accuracy": cv_results["test_accuracy"],
    "Recall": cv_results["test_recall"],
    "Precision": cv_results["test_precision"],
    "F1 score": cv_results["test_f1"]
}

table2_rows = []

for metric_name, scores in metric_mapping.items():

    mean_value = np.mean(
        scores
    )

    sd_value = np.std(
        scores,
        ddof=1
    )

    standard_error = (
        sd_value
        /
        np.sqrt(
            len(scores)
        )
    )

    ci_lower = (
        mean_value
        -
        t_crit
        *
        standard_error
    )

    ci_upper = (
        mean_value
        +
        t_crit
        *
        standard_error
    )

    table2_rows.append(
        {
            "Performance": metric_name,
            "Mean": mean_value,
            "SD": sd_value,
            "CI_lower": ci_lower,
            "CI_upper": ci_upper
        }
    )

table2_df = pd.DataFrame(
    table2_rows
)

table2_df.to_csv(
    RESULT_DIR /
    "Table2_TRUST_5fold_CV.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 70)
print("Table 2: five-fold cross-validation")
print("=" * 70)

print(
    "Metric       Mean ± SD              95% CI"
)

print("-" * 70)

for _, row in table2_df.iterrows():

    print(
        f'{row["Performance"]:<12} '
        f'{row["Mean"]:.4f} ± '
        f'{row["SD"]:.4f}    '
        f'({row["CI_lower"]:.4f}, '
        f'{row["CI_upper"]:.4f})'
    )

print("=" * 70)

# ============================================================
# Fit final model on the complete 80% training partition
# ============================================================

pipeline.fit(
    X_train,
    y_train
)

best_model = pipeline

# ============================================================
# Held-out validation prediction
# ============================================================

y_prob = (
    best_model
    .predict_proba(
        X_test
    )[:, 1]
)

y_pred = (
    best_model
    .predict(
        X_test
    )
)

# ============================================================
# Held-out validation performance
# ============================================================

tn, fp, fn, tp = (
    confusion_matrix(
        y_test,
        y_pred
    ).ravel()
)

accuracy = accuracy_score(
    y_test,
    y_pred
)

sensitivity = recall_score(
    y_test,
    y_pred
)

specificity = (
    tn /
    (tn + fp)
)

ppv = precision_score(
    y_test,
    y_pred
)

npv = (
    tn /
    (tn + fn)
)

f1 = f1_score(
    y_test,
    y_pred
)

auc = roc_auc_score(
    y_test,
    y_prob
)

ap = average_precision_score(
    y_test,
    y_prob
)

brier = brier_score_loss(
    y_test,
    y_prob
)

logloss = log_loss(
    y_test,
    y_prob
)

youden_index = (
    sensitivity
    +
    specificity
    -
    1
)

heldout_metrics_df = pd.DataFrame(
    [
        {
            "N": len(y_test),
            "Events": int(y_test.sum()),
            "Event_rate": y_test.mean(),
            "Accuracy": accuracy,
            "Sensitivity": sensitivity,
            "Specificity": specificity,
            "PPV": ppv,
            "NPV": npv,
            "F1": f1,
            "AUROC": auc,
            "Average_precision": ap,
            "Brier_score": brier,
            "Log_loss": logloss,
            "Youden_index": youden_index,
            "TN": tn,
            "FP": fp,
            "FN": fn,
            "TP": tp
        }
    ]
)

heldout_metrics_df.to_csv(
    RESULT_DIR /
    "TRUST_heldout_validation_metrics.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 70)
print("Held-out validation performance")
print("=" * 70)

print(
    heldout_metrics_df.to_string(
        index=False,
        float_format=lambda x:
        f"{x:.4f}"
    )
)

# ============================================================
# Formal logistic calibration function
# ============================================================

def calculate_logistic_calibration(
    y_true,
    predicted_probability
):
    """
    Estimate formal calibration intercept and slope using
    individual-level logistic recalibration:
        logit[P(Y=1)] =
        alpha + beta * logit(predicted probability)
    Ideal calibration:
        intercept = 0
        slope = 1
    """

    y_true = np.asarray(
        y_true
    )

    predicted_probability = np.asarray(
        predicted_probability
    )

    eps = 1e-6

    p = np.clip(
        predicted_probability,
        eps,
        1 - eps
    )

    logit_p = np.log(
        p /
        (1 - p)
    ).reshape(
        -1,
        1
    )

    calibration_model = LogisticRegression(
        penalty=None,
        solver="lbfgs",
        max_iter=2000
    )

    calibration_model.fit(
        logit_p,
        y_true
    )

    intercept = (
        calibration_model
        .intercept_[0]
    )

    slope = (
        calibration_model
        .coef_[0][0]
    )

    return (
        intercept,
        slope
    )

(
    formal_calibration_intercept,
    formal_calibration_slope
) = calculate_logistic_calibration(
    y_test,
    y_prob
)

print(
    f"\nFormal logistic calibration intercept: "
    f"{formal_calibration_intercept:.4f}"
)

print(
    f"Formal logistic calibration slope: "
    f"{formal_calibration_slope:.4f}"
)

# ============================================================
# Figure 4a: ROC curve
# ============================================================

fig, ax = plt.subplots(
    figsize=(9, 8)
)

fpr, tpr, _ = roc_curve(
    y_test,
    y_prob
)

ax.plot(
    fpr,
    tpr,
    color="black",
    linestyle="-",
    linewidth=2,
    label=f"AUROC = {auc:.4f}"
)

ax.plot(
    [0, 1],
    [0, 1],
    "k--",
    alpha=0.5,
    linewidth=1.5,
    label="Random classifier"
)

ax.set_xlim(
    0,
    1
)

ax.set_ylim(
    0,
    1
)

ax.set_xticks(
    np.arange(
        0,
        1.01,
        0.2
    )
)

ax.set_yticks(
    np.arange(
        0,
        1.01,
        0.2
    )
)

ax.set_xlabel(
    "False Positive Rate",
    fontsize=12
)

ax.set_ylabel(
    "True Positive Rate",
    fontsize=12
)

ax.set_title(
    "ROC Curve",
    fontsize=12,
    fontweight="bold"
)

ax.legend(
    fontsize=11,
    loc="lower right"
)

ax.tick_params(
    labelsize=12
)

fig.tight_layout()

fig.savefig(
    FIGURE_DIR /
    "Figure4a_ROC.png",
    **SAVE_KW
)

plt.close(fig)

# ============================================================
# Figure 4b: empirical precision-recall curve
# ============================================================
# The empirical PR curve is plotted directly without artificial
# precision-envelope interpolation.
# ============================================================

precision_curve, recall_curve, _ = (
    precision_recall_curve(
        y_test,
        y_prob
    )
)

prevalence = (
    y_test.mean()
)

fig, ax = plt.subplots(
    figsize=(9, 8)
)

ax.plot(
    recall_curve,
    precision_curve,
    color="black",
    linestyle="-",
    linewidth=2,
    label=f"AP = {ap:.4f}"
)

ax.axhline(
    y=prevalence,
    color="gray",
    linestyle="--",
    linewidth=1.5,
    label=(
        f"No-skill baseline = "
        f"{prevalence:.4f}"
    )
)

ax.set_xlim(
    0,
    1
)

ax.set_ylim(
    0,
    1
)

ax.set_xticks(
    np.arange(
        0,
        1.01,
        0.2
    )
)

ax.set_yticks(
    np.arange(
        0,
        1.01,
        0.2
    )
)

ax.set_xlabel(
    "Recall",
    fontsize=12
)

ax.set_ylabel(
    "Precision",
    fontsize=12
)

ax.set_title(
    "Precision-Recall Curve",
    fontsize=12,
    fontweight="bold"
)

ax.legend(
    fontsize=11,
    loc="upper right"
)

ax.tick_params(
    labelsize=12
)

fig.tight_layout()

fig.savefig(
    FIGURE_DIR /
    "Figure4b_PR.png",
    **SAVE_KW
)

plt.close(fig)

# ============================================================
# Figure 4c: calibration plot
# ============================================================

frac_pos, mean_pred = (
    calibration_curve(
        y_test,
        y_prob,
        n_bins=10,
        strategy="uniform"
    )
)

fig, ax = plt.subplots(
    figsize=(9, 8)
)

ax.plot(
    mean_pred,
    frac_pos,
    color=COLOR_CAL,
    linestyle="-",
    marker="D",
    markersize=5,
    linewidth=2,
    label="Observed calibration"
)

ax.plot(
    [0, 1],
    [0, 1],
    "k--",
    alpha=0.5,
    linewidth=1.5,
    label="Perfect calibration"
)

# ------------------------------------------------------------
# Descriptive linear fit through the binned calibration points
# This line is not the formal calibration slope.
# ------------------------------------------------------------

valid_mask = (
    ~np.isnan(mean_pred)
    &
    ~np.isnan(frac_pos)
)

descriptive_slope = np.nan
descriptive_intercept = np.nan
descriptive_r2 = np.nan

if np.sum(valid_mask) > 1:

    descriptive_model = (
        LinearRegression()
    )

    descriptive_model.fit(
        mean_pred[
            valid_mask
        ].reshape(
            -1,
            1
        ),
        frac_pos[
            valid_mask
        ]
    )

    descriptive_slope = (
        descriptive_model
        .coef_[0]
    )

    descriptive_intercept = (
        descriptive_model
        .intercept_
    )

    descriptive_r2 = (
        descriptive_model
        .score(
            mean_pred[
                valid_mask
            ].reshape(
                -1,
                1
            ),
            frac_pos[
                valid_mask
            ]
        )
    )

    x_line = np.linspace(
        0,
        1,
        200
    )

    y_line = (
        descriptive_model
        .predict(
            x_line.reshape(
                -1,
                1
            )
        )
    )

    ax.plot(
        x_line,
        y_line,
        "r--",
        linewidth=2,
        label=(
            "Descriptive linear fit: "
            f"y={descriptive_slope:.2f}x"
            f"{descriptive_intercept:+.2f}, "
            f"R²={descriptive_r2:.3f}"
        )
    )

# ------------------------------------------------------------
# Calibration summary box
# ------------------------------------------------------------

calibration_text = (
    f"Brier Score: {brier:.4f}\n"
    f"Log Loss: {logloss:.4f}"
)

ax.text(
    0.05,
    0.95,
    calibration_text,
    transform=ax.transAxes,
    fontsize=11,
    ha="left",
    va="top",
    bbox=dict(
        boxstyle="round",
        facecolor="wheat",
        alpha=0.5
    )
)

ax.set_xlim(
    0,
    1
)

ax.set_ylim(
    0,
    1
)

ax.set_xticks(
    np.arange(
        0,
        1.01,
        0.2
    )
)

ax.set_yticks(
    np.arange(
        0,
        1.01,
        0.2
    )
)

ax.set_xlabel(
    "Mean Predicted Probability",
    fontsize=12
)

ax.set_ylabel(
    "Fraction of Positives",
    fontsize=12
)

ax.set_title(
    "Calibration Curve",
    fontsize=12,
    fontweight="bold"
)

ax.legend(
    fontsize=10,
    loc="lower right"
)

ax.tick_params(
    labelsize=12
)

fig.tight_layout()

fig.savefig(
    FIGURE_DIR /
    "Figure4c_Calibration.png",
    **SAVE_KW
)

plt.close(fig)

print(
    f"\nDescriptive binned linear-fit slope: "
    f"{descriptive_slope:.4f}"
)

print(
    f"Descriptive binned linear-fit intercept: "
    f"{descriptive_intercept:.4f}"
)

print(
    f"Descriptive binned linear-fit R²: "
    f"{descriptive_r2:.4f}"
)

# ============================================================
# Figure 4d: prediction-probability distribution
# ============================================================

neg_probs = (
    y_prob[
        np.asarray(y_test) == 0
    ]
)

pos_probs = (
    y_prob[
        np.asarray(y_test) == 1
    ]
)

fig, ax = plt.subplots(
    figsize=(9, 8)
)

ax.hist(
    neg_probs,
    bins=30,
    alpha=0.60,
    color=COLOR_NEG,
    edgecolor="white",
    density=True,
    label=f"Negative (n={len(neg_probs)})"
)

ax.hist(
    pos_probs,
    bins=30,
    alpha=0.60,
    color=COLOR_POS,
    edgecolor="white",
    density=True,
    label=f"Positive (n={len(pos_probs)})"
)

# ------------------------------------------------------------
# KDE curves
# ------------------------------------------------------------

try:

    from scipy.stats import gaussian_kde

    x_range = np.linspace(
        0,
        1,
        300
    )

    if len(neg_probs) > 1:

        kde_neg = gaussian_kde(
            neg_probs
        )

        ax.plot(
            x_range,
            kde_neg(
                x_range
            ),
            color=COLOR_NEG,
            linewidth=2
        )

    if len(pos_probs) > 1:

        kde_pos = gaussian_kde(
            pos_probs
        )

        ax.plot(
            x_range,
            kde_pos(
                x_range
            ),
            color=COLOR_POS,
            linewidth=2
        )

except ImportError:

    print(
        "SciPy not available; "
        "KDE curves were skipped."
    )

ax.axvline(
    x=0.50,
    color="gray",
    linestyle=":",
    linewidth=2,
    alpha=0.8,
    label="Default threshold = 0.50"
)

ax.set_xlim(
    0,
    1
)

ax.set_xticks(
    np.arange(
        0,
        1.01,
        0.2
    )
)

ax.set_xlabel(
    "Predicted Probability",
    fontsize=12
)

ax.set_ylabel(
    "Density",
    fontsize=12
)

ax.set_title(
    "Prediction Probability Distribution by Class",
    fontsize=12,
    fontweight="bold"
)

ax.legend(
    fontsize=11
)

ax.tick_params(
    labelsize=12
)

fig.tight_layout()

fig.savefig(
    FIGURE_DIR /
    "Figure4d_Probability_Distribution.png",
    **SAVE_KW
)

plt.close(fig)

# ============================================================
# Supplementary Figure 2: feature importance
# ============================================================

rf_clf = (
    best_model
    .named_steps["clf"]
)

feature_names = (
    best_model
    .named_steps["prep"]
    .get_feature_names_out()
)

importance = (
    rf_clf
    .feature_importances_
)

top_n = 15

top_idx = np.argsort(
    importance
)[-top_n:]

top_feature_names = (
    feature_names[
        top_idx
    ]
)

top_importance = (
    importance[
        top_idx
    ]
)

colors = plt.cm.Blues(
    np.linspace(
        0.4,
        0.9,
        len(top_idx)
    )
)

fig, ax = plt.subplots(
    figsize=(9, 8)
)

ax.barh(
    range(
        len(top_idx)
    ),
    top_importance,
    color=colors,
    edgecolor="white"
)

ax.set_yticks(
    range(
        len(top_idx)
    )
)

ax.set_yticklabels(
    [
        name.replace(
            "prep__",
            ""
        )
        for name
        in top_feature_names
    ],
    fontsize=11
)

ax.set_xlabel(
    "Feature Importance",
    fontsize=12
)

ax.set_title(
    "Top 15 Feature Importances",
    fontsize=12,
    fontweight="bold"
)

ax.tick_params(
    labelsize=12
)

fig.tight_layout()

fig.savefig(
    FIGURE_DIR /
    "Supplementary_Figure2_Feature_Importance.png",
    **SAVE_KW
)

plt.close(fig)

# ============================================================
# Figure 4f: decision-curve analysis
# ============================================================
# Net benefit:
#     NB = TP/N - FP/N * pt/(1-pt)
# The clinically relevant interval is defined as the range in
# which the model provides greater net benefit than BOTH the
# treat-all and treat-none strategies.
# ============================================================

thresholds_dca = np.arange(
    0.01,
    1.00,
    0.01
)

n = len(
    y_test
)

prevalence = (
    y_test.mean()
)

# ------------------------------------------------------------
# Treat-all net benefit
# ------------------------------------------------------------

nb_all = (
    prevalence
    -
    (1 - prevalence)
    *
    thresholds_dca
    /
    (1 - thresholds_dca)
)

# ------------------------------------------------------------
# RF model net benefit
# ------------------------------------------------------------

nb_model = []

y_test_array = np.asarray(
    y_test
)

for pt in thresholds_dca:

    pred_positive = (
        y_prob >= pt
    )

    tp_dca = np.sum(
        pred_positive
        &
        (y_test_array == 1)
    )

    fp_dca = np.sum(
        pred_positive
        &
        (y_test_array == 0)
    )

    nb = (
        tp_dca / n
        -
        fp_dca / n
        *
        pt / (1 - pt)
    )

    nb_model.append(
        nb
    )

nb_model = np.asarray(
    nb_model
)

# ============================================================
# Identify threshold ranges where the model outperforms BOTH
# reference strategies
# ============================================================

better_than_both = (
    (nb_model > nb_all)
    &
    (nb_model > 0)
)

def get_continuous_ranges(
    boolean_mask,
    probability_thresholds
):
    """
    Convert a boolean mask into continuous threshold ranges.
    """

    indices = np.where(
        boolean_mask
    )[0]

    if len(indices) == 0:
        return []

    ranges = []

    start = indices[0]
    end = indices[0]

    for idx in indices[1:]:

        if idx == end + 1:

            end = idx

        else:

            ranges.append(
                (
                    probability_thresholds[
                        start
                    ],
                    probability_thresholds[
                        end
                    ]
                )
            )

            start = idx
            end = idx

    ranges.append(
        (
            probability_thresholds[
                start
            ],
            probability_thresholds[
                end
            ]
        )
    )

    return ranges

benefit_ranges = (
    get_continuous_ranges(
        better_than_both,
        thresholds_dca
    )
)

def format_ranges(
    ranges
):

    if not ranges:
        return "None"

    return ", ".join(
        [
            f"{start:.2f}–{end:.2f}"
            for start, end
            in ranges
        ]
    )

benefit_range_text = (
    format_ranges(
        benefit_ranges
    )
)

# ============================================================
# Maximum model net benefit
# ============================================================

best_idx = np.argmax(
    nb_model
)

best_threshold = (
    thresholds_dca[
        best_idx
    ]
)

best_nb = (
    nb_model[
        best_idx
    ]
)

print("\n" + "=" * 70)
print("Decision-curve analysis")
print("=" * 70)

print(
    f"Model > both Treat All and Treat None: "
    f"{benefit_range_text}"
)

print(
    f"Maximum net benefit: "
    f"{best_nb:.4f}"
)

print(
    f"Probability threshold at maximum NB: "
    f"{best_threshold:.2f}"
)

# ============================================================
# Figure 4f
# ============================================================

fig, ax = plt.subplots(
    figsize=(9, 8)
)

ax.plot(
    thresholds_dca,
    nb_model,
    color=COLOR_DCA,
    linestyle="-",
    linewidth=2,
    label="RF model"
)

ax.plot(
    thresholds_dca,
    nb_all,
    color="black",
    linestyle="--",
    linewidth=1.5,
    alpha=0.7,
    label="Treat all"
)

ax.axhline(
    y=0,
    color="gray",
    linestyle="-",
    linewidth=1.5,
    alpha=0.7,
    label="Treat none"
)

# ------------------------------------------------------------
# Mark maximum model net benefit
# ------------------------------------------------------------

ax.plot(
    best_threshold,
    best_nb,
    marker="o",
    color="black",
    markersize=7,
    linestyle="None"
)

# ------------------------------------------------------------
# Information box
# ------------------------------------------------------------

info_text = (
    f"Model > both references: "
    f"{benefit_range_text}\n"
    f"Maximum NB = {best_nb:.4f} "
    f"at p = {best_threshold:.2f}"
)

ax.text(
    0.04,
    0.96,
    info_text,
    transform=ax.transAxes,
    fontsize=11,
    ha="left",
    va="top",
    linespacing=1.4,
    bbox=dict(
        boxstyle="round",
        facecolor="white",
        alpha=0.90,
        edgecolor="gray"
    )
)

ax.set_xlim(
    0,
    1
)

# TRUST has low outcome prevalence and comparatively smallnet-benefit values;
# a narrower y-axis improves readability.
ax.set_ylim(
    -0.05,
    0.30
)

ax.set_xticks(
    np.arange(
        0,
        1,
        0.2
    )
)

ax.set_xlabel(
    "Threshold Probability",
    fontsize=12
)

ax.set_ylabel(
    "Net Benefit",
    fontsize=12
)

ax.set_title(
    "Decision Curve Analysis",
    fontsize=12,
    fontweight="bold"
)

ax.legend(
    fontsize=11,
    loc="upper right"
)

ax.tick_params(
    labelsize=12
)

fig.tight_layout()

fig.savefig(
    FIGURE_DIR /
    "Figure4f_DCA.png",
    **SAVE_KW
)

plt.close(fig)

# ============================================================
# Save calibration and DCA summary
# ============================================================

supplementary_metrics_df = pd.DataFrame(
    [
        {
            "Brier_score":
                brier,

            "Log_loss":
                logloss,

            "Descriptive_binned_linear_fit_slope":
                descriptive_slope,

            "Descriptive_binned_linear_fit_intercept":
                descriptive_intercept,

            "Descriptive_binned_linear_fit_R2":
                descriptive_r2,

            "Formal_calibration_intercept":
                formal_calibration_intercept,

            "Formal_calibration_slope":
                formal_calibration_slope,

            "Maximum_DCA_net_benefit":
                best_nb,

            "Probability_threshold_at_maximum_DCA_net_benefit":
                best_threshold,

            "DCA_range_better_than_both_references":
                benefit_range_text
        }
    ]
)

supplementary_metrics_df.to_csv(
    RESULT_DIR /
    "TRUST_calibration_and_DCA_metrics.csv",
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# Save fitted TRUST model
# ============================================================

model_path = (
    MODEL_DIR /
    "TRUST_model_thr16.pkl"
)

joblib.dump(
    best_model,
    model_path
)

# ============================================================
# Save modeling metadata
# ============================================================

metadata = {

    "clinical_target":
        "TRUST titer >= 1:16",

    "feature_cols":
        feature_cols,

    "categorical_cols":
        cat_cols,

    "ordinal_cols":
        ordinal_cols,

    "numerical_cols":
        num_cols,

    "split_ratio":
        "80% training / 20% held-out validation",

    "split_random_state":
        42,

    "smote_random_state":
        42,

    "model_random_state":
        42,

    "best_params":
        best_params,

    "classification_rule":
        (
            "pipeline.predict() used for threshold-dependent "
            "held-out validation metrics."
        ),

    "PR_curve":
        (
            "Empirical precision-recall curve without "
            "precision-envelope interpolation."
        ),

    "calibration":
        (
            "Ten uniform probability bins were used for the "
            "calibration plot. The red dashed linear fit is "
            "descriptive only. Formal calibration intercept "
            "and slope were estimated using individual-level "
            "logistic recalibration."
        ),

    "DCA_probability_range":
        "0.01 to 0.99",

    "Figure4e_note":
        (
            "Predictor missingness was generated separately "
            "from fixed descriptive summary values and is not "
            "included in this modeling script."
        )
}

joblib.dump(
    metadata,
    MODEL_DIR /
    "TRUST_model_metadata.pkl"
)

# ============================================================
# Completion summary
# ============================================================

print("\n" + "=" * 70)
print("TRUST analysis complete")
print("=" * 70)

print(
    f"Figures saved to: "
    f"{FIGURE_DIR.resolve()}"
)

print(
    f"Table 2 saved to: "
    f"{(RESULT_DIR / 'Table2_TRUST_5fold_CV.csv').resolve()}"
)

print(
    f"Held-out metrics saved to: "
    f"{(RESULT_DIR / 'TRUST_heldout_validation_metrics.csv').resolve()}"
)

print(
    f"Calibration/DCA metrics saved to: "
    f"{(RESULT_DIR / 'TRUST_calibration_and_DCA_metrics.csv').resolve()}"
)

print(
    f"Model saved to: "
    f"{model_path.resolve()}"
)

print(
    "\nFigure 4e is intentionally generated separately "
    "from fixed predictor-missingness summary values."
)

print(
    "\nAll TRUST model outputs were generated successfully."
)